//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCWebApplicationDAL.SystemEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GccSytemEntities : DbContext
    {
        public GccSytemEntities()
            : base("name=GccSytemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bulkmeter> bulkmeters { get; set; }
        public virtual DbSet<hydrant> hydrants { get; set; }
        public virtual DbSet<leakage> leakages { get; set; }
        public virtual DbSet<manhole> manholes { get; set; }
        public virtual DbSet<province> provinces { get; set; }
        public virtual DbSet<watervalf> watervalves { get; set; }
        public virtual DbSet<zimcity> zimcities { get; set; }
        public virtual DbSet<zimprovince> zimprovinces { get; set; }
        public virtual DbSet<zimtownship> zimtownships { get; set; }
        public virtual DbSet<vwStand> vwStands { get; set; }
        public virtual DbSet<vwleakageTown> vwleakageTowns { get; set; }
        public virtual DbSet<zimstand> zimstands { get; set; }
        public virtual DbSet<vwAccountsMkobaMatch> vwAccountsMkobaMatches { get; set; }
        public virtual DbSet<wMainLine> wMainLines { get; set; }
        public virtual DbSet<vwMkobaMatchingGrid> vwMkobaMatchingGrids { get; set; }
        public virtual DbSet<vwFinanceGridCoordinate> vwFinanceGridCoordinates { get; set; }
        public virtual DbSet<vwZimStandsWKT> vwZimStandsWKTs { get; set; }
    }
}
