//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCWebApplicationDAL.SystemEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class province
    {
        public int ID { get; set; }
        public string PROVINCE1 { get; set; }
        public Nullable<int> PROV_CODE { get; set; }
        public System.Data.Entity.Spatial.DbGeometry geom { get; set; }
        public string wkt { get; set; }
    }
}
