//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCWebApplicationDAL.SystemEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwStand
    {
        public int ID { get; set; }
        public string ACCOUNT_NAME { get; set; }
        public string ACC_NUMBER { get; set; }
        public string ADDRESS { get; set; }
        public string METER_NUMBER { get; set; }
        public string READING { get; set; }
        public string STANDID { get; set; }
        public string CONDITION { get; set; }
        public string RESIDENTS { get; set; }
        public string WATER_SOURCE { get; set; }
        public string ILLEGAL_CONNECTION_ { get; set; }
        public string BURST_PIPES__ { get; set; }
        public string TOILET_SEATS_ { get; set; }
        public string township { get; set; }
        public string townshipid { get; set; }
        public System.Data.Entity.Spatial.DbGeometry geom { get; set; }
        public Nullable<long> standtype { get; set; }
    }
}
