//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCWebApplicationDAL.SystemEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwZimStandsWKT
    {
        public int id { get; set; }
        public string Account { get; set; }
        public decimal CurrentPayment { get; set; }
        public decimal TOTAL { get; set; }
        public string Dept { get; set; }
        public string Cons_Code { get; set; }
        public string Active { get; set; }
        public string Name { get; set; }
        public string TOWNSHIPID { get; set; }
        public string STANDID { get; set; }
        public string METER_NUMBER { get; set; }
        public string READING { get; set; }
        public string CONDITION { get; set; }
        public string RESIDENTS { get; set; }
        public string WATER_SOURCE { get; set; }
        public string ILLEGAL_CONNECTION_ { get; set; }
        public string BURST_PIPES__ { get; set; }
        public string TOILET_SEATS_ { get; set; }
        public Nullable<double> xCoordinate { get; set; }
        public Nullable<double> yCoordinate { get; set; }
        public string wkt { get; set; }
    }
}
