//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCWebApplicationDAL.SystemEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class zimstand
    {
        public int id { get; set; }
        public string standid { get; set; }
        public Nullable<long> cityid { get; set; }
        public Nullable<long> standtype { get; set; }
        public string township { get; set; }
        public string townshipid { get; set; }
        public System.Data.Entity.Spatial.DbGeometry geom { get; set; }
    }
}
