//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCWebApplicationDAL.SystemEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class zimtownship
    {
        public int id { get; set; }
        public string Name { get; set; }
        public Nullable<double> SHAPE_Leng { get; set; }
        public Nullable<double> SHAPE_Area { get; set; }
        public Nullable<long> cityid { get; set; }
        public Nullable<long> townshipid { get; set; }
        public System.Data.Entity.Spatial.DbGeometry geom { get; set; }
    }
}
