//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCWebApplicationDAL.WaterAuditEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WaterAuditEntities : DbContext
    {
        public WaterAuditEntities()
            : base("name=WaterAuditEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<wHydrant> wHydrants { get; set; }
        public virtual DbSet<wLiteralLine> wLiteralLines { get; set; }
        public virtual DbSet<wServiceConnection> wServiceConnections { get; set; }
        public virtual DbSet<wValf> wValves { get; set; }
        public virtual DbSet<wWindsorPark> wWindsorParks { get; set; }
        public virtual DbSet<vwAffectedHous> vwAffectedHouses { get; set; }
        public virtual DbSet<vwStandConLiteral> vwStandConLiterals { get; set; }
        public virtual DbSet<vwStands2Valves> vwStands2Valves { get; set; }
    }
}
