//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCWebApplicationDAL.WaterAuditEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class wHydrant
    {
        public int id { get; set; }
        public string hydrant { get; set; }
        public Nullable<float> lat { get; set; }
        public Nullable<float> @long { get; set; }
        public System.Data.Entity.Spatial.DbGeometry geom { get; set; }
    }
}
