//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCWebApplicationDAL.WaterAuditEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class wServiceConnection
    {
        public int id { get; set; }
        public Nullable<long> Enabled { get; set; }
        public Nullable<long> ActiveFlag { get; set; }
        public string OwnedBy { get; set; }
        public string ManagedBy { get; set; }
        public string AccNumber { get; set; }
        public string AccHolder { get; set; }
        public string ServiceTyp { get; set; }
        public string MeterNumb { get; set; }
        public Nullable<float> Shape_Leng { get; set; }
        public Nullable<float> Shape_Area { get; set; }
        public Nullable<long> standid { get; set; }
        public Nullable<long> FacilityId { get; set; }
        public Nullable<float> lat { get; set; }
        public Nullable<float> @long { get; set; }
        public System.Data.Entity.Spatial.DbGeometry geom { get; set; }
    }
}
