//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCWebApplicationDAL.WaterAuditEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class wWindsorPark
    {
        public int id { get; set; }
        public Nullable<long> OBJECTID { get; set; }
        public Nullable<float> Shape_Leng { get; set; }
        public Nullable<float> Shape_Area { get; set; }
        public Nullable<long> standid { get; set; }
        public string standnum { get; set; }
        public System.Data.Entity.Spatial.DbGeometry geom { get; set; }
    }
}
